### ISSUE TITLE
Raspberry < 4B support

### ISSUE THREAD

**Issue by vanmil** [robocarstore/donkeycar-images#1]
Hi, 

I have a Raspberry 3B. I see that this image supports 4B. Is it correct that it does not work on the 3B? The problem I currently have is that no hotspot starts (after flashing the image and then booting the raspberry with that image). 

Thanks, Jelle

**Comment by sctse999** [comment]
Hi it does not currently support 3B because 3B wireless capabilities limitation. However, if you manually configure the wireless network under ```/etc/wpa_supplicant``` I guess it might have a chance to work. Let me know if it doesn't.

**Comment by Schultzy1310** [comment]
Editing the wpa_supplicant worked!

After joining both the Donkey and the iPhone to the same WiFi, it took a moment for the connection, but after that it was smooth! 

Thanks for this, this is going to be great for my middle school robotics club!

**Comment by sctse999** [comment]
@Schultzy1310 Great. Ping me on Donkey Car discord. I could share more with you the work i am doing for schools.
