### ISSUE TITLE
password for jetson nano

### ISSUE THREAD

**Issue by haroonhublikar12** [robocarstore/donkeycar-images#4]
hey i just downloaded and flashed my jetson nano with jetson nano image. what is the passsword for login?

**Comment by sctse999** [comment]
Hi, if you purchase the donkey car from us, the password is in the assembly guide.

**Comment by haroonhublikar12** [comment]
made my own diy car...

**Comment by sctse999** [comment]
added the info in README.md . The image for Nano is fully functional but relatively old. Let me know if you need anything else. Also welcome for any contribution.
