### ISSUE TITLE
new image

### ISSUE THREAD

**Issue by Yardkyn** [robocarstore/donkeycar-images#5]
could U upload new image after recent updates.
Because after instalation and conecting to car there is nothing in app
there is problem with setup

**Comment by sctse999** [comment]
What do you mean by recent update? The image should be self-sufficient and working. If you are referring to the latest donkey car version, it is on our todo list but not the highest priority. You can spend some time working on it and let us know.

**Comment by Yardkyn** [comment]
I will do spend more and update some informations
btw i work with piracer, and i found od discord, that some changes in version 4.2.1 it does work
https://discord.com/channels/662098530411741184/671604048218292233/882794735729770537
previously i made it work like in april, but later it stopted to work, i dont know why. 
And now my work is kind of lost, (deleted by mistake)
I am trying to follow steps on discord but unfortunately image 2021-05-27 which i assume is 4.2.1 is unavaible on drop box from link do download from git.
If someone would know where else i could find it.

**Comment by sctse999** [comment]
We do not plan to support PiRacer. This image is exclusively built for our version of donkey car at Robocar store.

**Comment by Yardkyn** [comment]
could You direct me to version 4.2.1, one of links of images doesnt work, and i think it might be this one :)

**Comment by Yardkyn** [comment]
https://drive.google.com/uc?export=download&confirm=5eLQ&id=19hYKLFnuD7l0YiKEilakvZvX3BYVRta3
