### ISSUE TITLE
Images don't run on Raspberry Pi 4B

### ISSUE THREAD

**Issue by ana-tah** [robocarstore/donkeycar-images#6]
I have run the following two images on Raspberry Pi 4B, versions' dates are: 2021-06-02 and 2020-10-14. Both failed to show the signs of compatibility with the hardware, and the returned error message was "this board requires newer software". Attached are the pictures.

![Capture](https://user-images.githubusercontent.com/92544108/194224468-a5f9aadf-0b99-43d8-8b7a-37fa92f8cb8a.PNG)
![20221004_210553](https://user-images.githubusercontent.com/92544108/194224488-a740f03a-52f1-4730-89af-1f9119637ee2.jpg)

**Comment by sctse999** [comment]
We will be releasing a new image in the next few days. Stay tuned.

**Comment by sctse999** [comment]
Image released. Please download and test.
