### ISSUE TITLE
Hotspot is not working, unable to connect

### ISSUE THREAD

**Issue by davidcaizwc** [robocarstore/donkeycar-images#8]
I tried both pre-built images 2022-11-03, 2022-10-27, unable to find any hotspot "donkey-xxxxx".

**Comment by xuxer** [comment]
I encountered the same problem

**Comment by sctse999** [comment]
The hotspot feature is removed but I cannot confirm which version it is removed.

**Comment by xuxer** [comment]
removed this feature？what a pity
